language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.5.1
install:
 # Install Django
 - pip install -q Django==$DJANGO_VERSION --use-mirrors
 # Install PEP8
 - pip install pep8 --use-mirrors
 # Install flake8
 - pip install flake8 --use-mirrors
 # Install dependencies
 - pip install -r ./requirements/tests.txt
 # Install django-cpe app
 - pip install -q . --use-mirrors
before_script:
 # Validate PEP8 in source and test file
 - "pep8 --exclude=migrations --ignore=E501,E225 src"
 - "pep8 --exclude=migrations --ignore=E501,E225 tests"
script:
 # Execute tests
 - py.test -q
# branch builds whitelist
branches:
  only:
    - master
    - develop
